version: "3"

networks:
    app-tier-fcommerce:
        driver: bridge
    external_network:
        external: true

services:
    fcommerce_web:
        container_name: fcommerce_web
        restart: always
        user: "0:0"
        build:
            context: .
            dockerfile: Dockerfile
        command: ./deployment/start-app
        networks:
            - app-tier-fcommerce
            - external_network
        env_file:
            - .env
        ports:
            - "127.0.0.1:8001:8000"

    fcommerce_redis:
        image: redis:alpine
        restart: always
        read_only: false
        container_name: fcommerce_redis
        command: redis-server --port 6390 --appendonly yes
        networks:
            - app-tier-fcommerce
            - external_network

    fcommerce_celery:
        container_name: fcommerce_celery
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        command: ./deployment/start-celery
        depends_on:
            - fcommerce_redis
        volumes:
            - .:/app
        env_file:
            - .env
        networks:
            - app-tier-fcommerce
            - external_network
              #    
              #    fcommerce_celery_flower:
              #        container_name: fcommerce_celery_flower
              #        build:
              #            context: .
              #            dockerfile: Dockerfile
              #        env_file:
              #            - .env
              #        restart: always
              #        volumes:
              #            - .:/app
              #        ports:
              #            - "127.0.0.1:5555:5555"
              #        command: celery -A core flower --address=0.0.0.0 --port=5555
              #        networks:
              #            - app-tier-fcommerce

