# Generated by Django 4.2.1 on 2023-06-21 12:10

import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookIntegrationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=700, verbose_name='Access Token')),
                ('business_id', models.CharField(max_length=500, verbose_name='Business ID')),
                ('catalog_id', models.CharField(max_length=500, verbose_name='Catalog ID')),
                ('page_id', models.CharField(max_length=500, verbose_name='Page ID')),
                ('page_data', models.JSONField(blank=True, null=True, verbose_name='Page Info')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_info', to=settings.AUTH_USER_MODEL, verbose_name='Merchant')),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
