# Generated by Django 4.2.1 on 2023-06-22 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebook_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookintegrationdata',
            name='access_token',
            field=models.CharField(max_length=700, unique=True, verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='facebookintegrationdata',
            name='business_id',
            field=models.CharField(max_length=500, unique=True, verbose_name='Business ID'),
        ),
        migrations.AlterField(
            model_name='facebookintegrationdata',
            name='catalog_id',
            field=models.CharField(max_length=500, unique=True, verbose_name='Catalog ID'),
        ),
        migrations.AlterField(
            model_name='facebookintegrationdata',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_info', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Merchant'),
        ),
        migrations.AlterField(
            model_name='facebookintegrationdata',
            name='page_id',
            field=models.CharField(max_length=500, unique=True, verbose_name='Page ID'),
        ),
    ]
