# Generated by Django 4.2.1 on 2023-06-04 08:55

import dirtyfields.dirtyfields
import django.contrib.auth.password_validation
from django.db import migrations, models
import merchants.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, validators=[merchants.validators.UnicodeMerchantNameValidator()], verbose_name='Name')),
                ('merchant_id', models.CharField(max_length=200, verbose_name='ID')),
                ('password', models.CharField(max_length=128, validators=[django.contrib.auth.password_validation.validate_password], verbose_name='Password')),
                ('publish_shop', models.BooleanField(default=False, verbose_name='Publish Shop')),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
