# Generated by Django 4.2.1 on 2023-06-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchant_is_active_alter_merchant_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='publish_shop',
            new_name='is_published',
        ),
    ]
