# Generated by Django 4.2.1 on 2023-06-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_alter_merchant_merchant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='integrate_facebook',
            field=models.BooleanField(default=False, verbose_name='Integrate Facebook'),
        ),
    ]
