# Generated by Django 4.2.1 on 2023-07-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_rename_publish_shop_merchant_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='signature_key',
            field=models.CharField(default='sldfjlksjdflkjsdfjeowifjlsdkjflksdf', max_length=500, unique=True, verbose_name='Signature Key'),
            preserve_default=False,
        ),
    ]
