# Generated by Django 4.2.1 on 2023-06-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_merchant_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='merchant_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='Merchant ID'),
        ),
    ]
