# Generated by Django 4.2.1 on 2023-07-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_merchant_signature_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='cancle_url',
            field=models.URLField(default='https://www.aamarpay.com', verbose_name='Cancel URL'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='failed_url',
            field=models.URLField(default='https://www.aamarpay.com', verbose_name='Failed URL'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='success_url',
            field=models.URLField(default='https://www.aamarpay.com', verbose_name='Success URL'),
        ),
    ]
