# Generated by Django 4.2.1 on 2023-06-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_alter_merchant_merchant_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchant',
            options={'ordering': ['-created_at']},
        ),
    ]
