# Generated by Django 4.2.1 on 2023-07-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_merchant_cancle_url_merchant_failed_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='cancle_url',
            new_name='cancel_url',
        ),
    ]
