# Generated by Django 4.2.1 on 2023-07-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_remove_merchantproduct_expiration_date_greater_than_today_and_more'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='customer_email',
            field=models.EmailField(default='dummy@aamarpay.com', max_length=200, verbose_name='Customer Email'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='customer_name',
            field=models.CharField(default='dummy', max_length=200, verbose_name='Customer Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='customer_phone_no',
            field=models.CharField(default='', max_length=100, verbose_name='Customer Phone No'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='products.merchantproduct'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='shipping_address',
            field=models.CharField(default='', max_length=500, verbose_name='Shipping Address'),
            preserve_default=False,
        ),
    ]
