# Generated by Django 4.2.1 on 2023-07-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_remove_merchantproduct_expiration_date_greater_than_today_and_more'),
        ('checkout', '0002_orderinfo_customer_email_orderinfo_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='products.merchantproduct'),
        ),
    ]
