# Generated by Django 4.2.1 on 2023-07-11 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0003_alter_orderinfo_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='merchant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='placed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Merchant'),
            preserve_default=False,
        ),
    ]
