# Generated by Django 4.2.1 on 2023-07-11 07:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_remove_merchantproduct_expiration_date_greater_than_today_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0004_orderinfo_merchant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderInfo',
            new_name='Order',
        ),
    ]
