# Generated by Django 4.2.1 on 2023-07-11 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payment_info', serialize=False, to='checkout.order', verbose_name='Order')),
                ('trnx_id', models.UUIDField(verbose_name='Transaction ID')),
                ('payment_status', models.IntegerField(choices=[(0, 'Initiated'), (1, 'Attempt'), (2, 'Successful'), (3, 'Cancled'), (4, 'Chargeback'), (5, 'On-Hold'), (6, 'Suspect'), (7, 'Faliled'), (8, 'Refunded'), (9, 'Incomplete'), (10, 'Refund-Void'), (11, 'Error-Customer-Refund'), (12, 'Chargeback-Refund'), (13, 'Missing-Authorised-Email')], default=0)),
                ('pg_response', models.JSONField(verbose_name='PG-Response')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(default='FCommerce Payment'),
        ),
    ]
