# Generated by Django 4.2.1 on 2023-07-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_orderpayment_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Initiated'), (1, 'Attempt'), (2, 'Successful'), (3, 'Cancled'), (4, 'Chargeback'), (5, 'On-Hold'), (6, 'Suspect'), (7, 'Faliled'), (8, 'Refunded'), (9, 'Incomplete'), (10, 'Refund-Void'), (11, 'Error-Customer-Refund'), (12, 'Chargeback-Refund'), (13, 'Missing-Authorised-Email')], default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='pg_response',
            field=models.JSONField(blank=True, null=True, verbose_name='PG-Response'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.UUIDField(default='ded6b049-409b-4df9-afd2-988cad890429', verbose_name='Transaction ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderPayment',
        ),
    ]
