# Generated by Django 4.2.1 on 2023-07-11 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_order_payment_status_order_pg_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Transaction ID'),
        ),
    ]
