# Generated by Django 4.2.1 on 2023-07-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_order_payment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_currency',
            field=models.CharField(blank=True, choices=[('BDT', 'BDT'), ('USD', 'USD')], max_length=3, null=True, verbose_name='Currency'),
        ),
    ]
