# Generated by Django 4.2.1 on 2023-07-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_alter_order_payment_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pg_response',
        ),
        migrations.AddField(
            model_name='order',
            name='pg_transaction_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
