# Generated by Django 4.2.1 on 2023-07-06 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAPINotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_response_status_code', models.IntegerField(verbose_name='Response Status Code')),
                ('api_response', models.JSONField(verbose_name='API Response')),
                ('action', models.CharField(choices=[('ADD', 'Add Product'), ('DEL', 'Delete Product'), ('UPD', 'Update Product'), ('GET', 'Retrieve Product'), ('GETCATITEM', 'Get Catalog Item'), ('GETPAGEINFO', 'Get Page Info'), ('GETOWNEDCATALOG', 'Get Owned Catalog'), ('GETOWNEDPAGES', 'Get Owned Pages')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
