# Generated by Django 4.2.1 on 2023-07-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_facebookapierrorlog_delete_facebookapinotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookapierrorlog',
            name='message',
            field=models.CharField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='facebookapierrorlog',
            name='api_response',
            field=models.JSONField(blank=True, null=True, verbose_name='API Response'),
        ),
        migrations.AlterField(
            model_name='facebookapierrorlog',
            name='api_response_status_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Response Status Code'),
        ),
    ]
