# Generated by Django 4.2.1 on 2023-06-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='retailer_id',
            field=models.CharField(max_length=100, verbose_name='Content ID'),
        ),
    ]
