# Generated by Django 4.2.1 on 2023-06-19 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_alter_product_category_alter_product_retailer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProducts',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product', verbose_name='Product')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Merchant')),
            ],
        ),
    ]
