# Generated by Django 4.2.1 on 2023-06-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_merchantproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='retailer_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Content ID'),
        ),
    ]
