# Generated by Django 4.2.1 on 2023-06-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_gtin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer_price_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_price_end_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_price_start_date',
        ),
    ]
