# Generated by Django 4.2.1 on 2023-06-19 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_remove_product_offer_price_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantproducts',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='owned_products', to=settings.AUTH_USER_MODEL, verbose_name='Merchant'),
        ),
        migrations.AlterField(
            model_name='merchantproducts',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='product_owner', serialize=False, to='products.product', verbose_name='Product'),
        ),
    ]
