# Generated by Django 4.2.1 on 2023-06-19 10:58

from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, validators=[products.validators.ExpirationDateValidator()], verbose_name='Expiration Date'),
        ),
    ]
