# Generated by Django 4.2.1 on 2023-06-20 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='expiration_date_greater_than_today',
        ),
        migrations.AlterField(
            model_name='product',
            name='retailer_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Retailer ID'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('expiration_date__gt', datetime.date(2023, 6, 20))), name='expiration_date_greater_than_today'),
        ),
    ]
