# Generated by Django 4.2.1 on 2023-06-22 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_product_expiration_date_greater_than_today_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='expiration_date_greater_than_today',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('expiration_date__gt', datetime.date(2023, 6, 22))), name='expiration_date_greater_than_today'),
        ),
    ]
