# Generated by Django 4.2.1 on 2023-06-22 10:21

from django.db import migrations
import products.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_expiration_date_greater_than_today_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='retailer_id',
            field=products.fields.RetailerIDField(editable=False, max_length=100, unique=True, verbose_name='Retailer ID'),
        ),
    ]
