# Generated by Django 4.2.1 on 2023-06-26 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_price_should_be_greater_than_0'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='expiration_date_greater_than_today',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('expiration_date__gt', datetime.date(2023, 6, 26))), name='expiration_date_greater_than_today'),
        ),
    ]
