# Generated by Django 4.2.1 on 2023-06-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_product_expiration_date_greater_than_today_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='return_policy_days',
        ),
    ]
