# Generated by Django 4.2.1 on 2023-07-03 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_facebook_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='expiration_date_greater_than_today',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('expiration_date__gt', datetime.date(2023, 7, 3))), name='expiration_date_greater_than_today'),
        ),
    ]
