# Generated by Django 4.2.1 on 2023-07-04 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_product_expiration_date_greater_than_today_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='expiration_date_greater_than_today',
        ),
        migrations.AlterField(
            model_name='product',
            name='importer_name',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Importer Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Product Type'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('expiration_date__gt', datetime.date(2023, 7, 4))), name='expiration_date_greater_than_today'),
        ),
    ]
