# Generated by Django 4.2.1 on 2023-07-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_product_additional_image_urls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Sale Price'),
        ),
    ]
