# Generated by Django 4.2.1 on 2023-07-04 12:10

from django.db import migrations
import products.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_product_price_alter_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gtin',
            field=products.fields.GTINField(editable=False, max_length=50, verbose_name='Global Trade Item Number'),
        ),
    ]
