# Generated by Django 4.2.1 on 2023-07-05 08:14

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import products.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0026_alter_product_gtin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.URLField(max_length=500, verbose_name='Product URL')),
                ('image_url', models.URLField(max_length=500, verbose_name='Image URL')),
                ('currency', models.CharField(choices=[('BDT', 'BDT'), ('USD', 'USD')], max_length=3, verbose_name='Currency')),
                ('price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Price')),
                ('retailer_id', products.fields.RetailerIDField(editable=False, max_length=100, unique=True, verbose_name='Retailer ID')),
                ('gtin', products.fields.GTINField(editable=False, max_length=50, verbose_name='Global Trade Item Number')),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('refurbished', 'Refurbished'), ('used', 'Used'), ('used_like_new', 'Used Like New'), ('used_good', 'Used Good'), ('used_fair', 'Used Fair'), ('cpo', 'CPO'), ('open_box_new', 'Open Box New')], max_length=50, null=True, verbose_name='Condition')),
                ('availability', models.CharField(blank=True, choices=[('in stock', 'In Stock'), ('out of stock', 'Out of Stock'), ('preorder', 'Preorder'), ('available for order', 'Available for Order'), ('discontinued', 'Discontinued'), ('pending', 'Pending')], max_length=100, null=True, verbose_name='Availability')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Category')),
                ('color', models.CharField(blank=True, null=True, verbose_name='Color')),
                ('visibility', models.CharField(blank=True, choices=[('staging', 'Staging'), ('published', 'Published')], default='published', max_length=50, null=True, verbose_name='Visibility')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('additional_image_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), blank=True, null=True, size=None, verbose_name='Additional Images')),
                ('additional_variant_attributes', models.JSONField(blank=True, null=True, verbose_name='Additional Varients')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('size', models.CharField(blank=True, null=True, verbose_name='Size')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Short Description')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Sale Price')),
                ('sale_price_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Sale Price Start Date')),
                ('sale_price_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Sale Price End Date')),
                ('product_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Product Type')),
                ('pattern', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pattern')),
                ('origin_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country')),
                ('material', models.CharField(blank=True, max_length=200, null=True, verbose_name='Material')),
                ('importer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Importer Name')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('unisex', 'Unisex')], max_length=20, null=True, verbose_name='Gender')),
                ('facebook_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook ID')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MerchantProducts',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddConstraint(
            model_name='merchantproduct',
            constraint=models.CheckConstraint(check=models.Q(('expiration_date__gt', datetime.date(2023, 7, 5))), name='expiration_date_greater_than_today'),
        ),
        migrations.AddConstraint(
            model_name='merchantproduct',
            constraint=models.CheckConstraint(check=models.Q(('price__gt', 0)), name='Price should be greater than 0'),
        ),
        migrations.AlterUniqueTogether(
            name='merchantproduct',
            unique_together={('merchant', 'retailer_id')},
        ),
    ]
