# Generated by Django 4.2.1 on 2023-07-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_merchantproduct_gtin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantproduct',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='merchantproduct',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sale Price'),
        ),
    ]
