# Generated by Django 4.2.1 on 2023-07-06 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_merchantproduct_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='merchantproduct',
            name='expiration_date_greater_than_today',
        ),
        migrations.AlterField(
            model_name='merchantproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='merchantproduct',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Sale Price'),
        ),
        migrations.AddConstraint(
            model_name='merchantproduct',
            constraint=models.CheckConstraint(check=models.Q(('expiration_date__gt', datetime.date(2023, 7, 6))), name='expiration_date_greater_than_today'),
        ),
    ]
