# Generated by Django 4.2.1 on 2023-07-10 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_remove_merchantproduct_expiration_date_greater_than_today_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='merchantproduct',
            name='expiration_date_greater_than_today',
        ),
        migrations.AddConstraint(
            model_name='merchantproduct',
            constraint=models.CheckConstraint(check=models.Q(('expiration_date__gt', datetime.date(2023, 7, 10))), name='expiration_date_greater_than_today'),
        ),
    ]
